using Microsoft.EntityFrameworkCore.Migrations;

namespace Medico.Api.Migrations
{
    public partial class Fill_IcdCode_Table : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"INSERT INTO IcdCode (Code, Name, Description) VALUES 
                                  ('001.00','CHOLERA D/T VIB CHOLERAE','none'),
                                  ('001.10','CHOLERA D/T VIB EL TOR','none'),
                                  ('001.90','CHOLERA NOS','none'),
                                  ('002.00','TYPHOID FEVER','none'),
                                  ('002.10','PARATYPHOID FEVER A','none'),
                                  ('002.20','PARATYPHOID FEVER B','none'),
                                  ('002.30','PARATYPHOID FEVER C','none'),
                                  ('002.90','PARATYPHOID FEVER NOS','none'),
                                  ('003.00','SALMONELLA ENTERITIS','none'),
                                  ('003.10','SALMONELLA SEPTICEMIA','none'),
                                  ('003.20','LOCAL SALMONELLA INF NOS','none'),
                                  ('003.21','SALMONELLA MENINGITIS','none'),
                                  ('003.22','SALMONELLA PNEUMONIA','none'),
                                  ('003.23','SALMONELLA ARTHRITIS','none'),
                                  ('003.24','SALMONELLA OSTEOMYELITIS','none'),
                                  ('003.29','LOCAL SALMONELLA INF NEC','none'),
                                  ('003.80','SALMONELLA INFECTION NEC','none'),
                                  ('003.90','SALMONELLA INFECTION NOS','none'),
                                  ('004.00','SHIGELLA DYSENTERIAE','none'),
                                  ('004.10','SHIGELLA FLEXNERI','none'),
                                  ('004.20','SHIGELLA BOYDII','none'),
                                  ('004.30','SHIGELLA SONNEI','none'),
                                  ('004.80','SHIGELLA INFECTION NEC','none'),
                                  ('004.90','SHIGELLOSIS NOS','none'),
                                  ('005.00','STAPH FOOD POISONING','none'),
                                  ('005.10','BOTULISM','none'),
                                  ('005.20','FOOD POIS D/T C. PERFRIN','none'),
                                  ('005.30','FOOD POIS: CLOSTRID NEC','none'),
                                  ('005.40','FOOD POIS: V. PARAHAEM','none'),
                                  ('005.81','FOOD POISN D/T V. VULNIF','none'),
                                  ('005.89','BACT FOOD POISONING NEC','none'),
                                  ('005.90','FOOD POISONING NOS','none'),
                                  ('006.00','AC AMEBIASIS W/O ABSCESS','none'),
                                  ('006.10','CHR AMEBIASIS W/O ABSCES','none'),
                                  ('006.20','AMEBIC NONDYSENT COLITIS','none'),
                                  ('006.30','AMEBIC LIVER ABSCESS','none'),
                                  ('006.40','AMEBIC LUNG ABSCESS','none'),
                                  ('006.50','AMEBIC BRAIN ABSCESS','none'),
                                  ('006.60','AMEBIC SKIN ULCERATION','none'),
                                  ('006.80','AMEBIC INFECTION NEC','none'),
                                  ('006.90','AMEBIASIS NOS','none'),
                                  ('007.00','BALANTIDIASIS','none'),
                                  ('007.10','GIARDIASIS','none'),
                                  ('007.20','COCCIDIOSIS','none'),
                                  ('007.30','INTEST TRICHOMONIASIS','none'),
                                  ('007.40','CRYPTOSPORIDIOSIS','none'),
                                  ('007.50','CYCLOSPORIASIS','none'),
                                  ('007.80','PROTOZOAL INTEST DIS NEC','none'),
                                  ('007.90','PROTOZOAL INTEST DIS NOS','none'),
                                  ('008.00','INTEST INFEC E COLI NOS','none'),
                                  ('008.01','INT INF E COLI ENTRPATH','none'),
                                  ('008.02','INT INF E COLI ENTRTOXGN','none'),
                                  ('008.03','INT INF E COLI ENTRNVSV','none'),
                                  ('008.04','INT INF E COLI ENTRHMRG','none'),
                                  ('008.09','INT INF E COLI SPCF NEC','none'),
                                  ('008.10','ARIZONA ENTERITIS','none'),
                                  ('008.20','AEROBACTER ENTERITIS','none'),
                                  ('008.30','PROTEUS ENTERITIS','none'),
                                  ('008.41','STAPHYLOCOCC ENTERITIS','none'),
                                  ('008.42','PSEUDOMONAS ENTERITIS','none'),
                                  ('008.43','INT INFEC CAMPYLOBACTER','none'),
                                  ('008.44','INT INF YRSNIA ENTRCLTCA','none'),
                                  ('008.45','INT INF CLSTRDIUM DFCILE','none'),
                                  ('008.46','INTES INFEC OTH ANEROBES','none'),
                                  ('008.47','INT INF OTH GRM NEG BCTR','none'),
                                  ('008.49','BACTERIAL ENTERITIS NEC','none'),
                                  ('008.50','BACTERIAL ENTERITIS NOS','none'),
                                  ('008.61','INTES INFEC ROTAVIRUS','none'),
                                  ('008.62','INTES INFEC ADENOVIRUS','none'),
                                  ('008.63','INT INF NORWALK VIRUS','none'),
                                  ('008.64','INT INF OTH SML RND VRUS','none'),
                                  ('008.65','INTES INFEC CALCIVIRUS','none'),
                                  ('008.66','INTES INFEC ASTROVIRUS','none'),
                                  ('008.67','INT INF ENTEROVIRUS NEC','none'),
                                  ('008.69','OTHER VIRAL INTES INFEC','none'),
                                  ('008.80','VIRAL ENTERITIS NOS','none'),
                                  ('009.00','INFECTIOUS ENTERITIS NOS','none'),
                                  ('009.10','ENTERITIS OF INFECT ORIG','none'),
                                  ('009.20','INFECTIOUS DIARRHEA NOS','none'),
                                  ('009.30','DIARRHEA OF INFECT ORIG','none'),
                                  ('010.00','PRIM TB COMPLEX-UNSPEC','none'),
                                  ('010.01','PRIM TB COMPLEX-NO EXAM','none'),
                                  ('010.02','PRIM TB COMPLEX-EXM UNKN','none'),
                                  ('010.03','PRIM TB COMPLEX-MICRO DX','none'),
                                  ('010.04','PRIM TB COMPLEX-CULT DX','none'),
                                  ('010.05','PRIM TB COMPLEX-HISTO DX','none'),
                                  ('010.06','PRIM TB COMPLEX-OTH TEST','none'),
                                  ('010.10','PRIM TB PLEURISY-UNSPEC','none'),
                                  ('010.11','PRIM TB PLEURISY-NO EXAM','none'),
                                  ('010.12','PRIM TB PLEUR-EXAM UNKN','none'),
                                  ('010.13','PRIM TB PLEURIS-MICRO DX','none'),
                                  ('010.14','PRIM TB PLEURISY-CULT DX','none'),
                                  ('010.15','PRIM TB PLEURIS-HISTO DX','none'),
                                  ('010.16','PRIM TB PLEURIS-OTH TEST','none'),
                                  ('010.80','PRIM PROG TB NEC-UNSPEC','none'),
                                  ('010.81','PRIM PROG TB NEC-NO EXAM','none'),
                                  ('010.82','PRIM PR TB NEC-EXAM UNKN','none'),
                                  ('010.83','PRIM PRG TB NEC-MICRO DX','none'),
                                  ('010.84','PRIM PROG TB NEC-CULT DX','none'),
                                  ('010.85','PRIM PRG TB NEC-HISTO DX','none'),
                                  ('010.86','PRIM PRG TB NEC-OTH TEST','none'),
                                  ('010.90','PRIMARY TB NOS-UNSPEC','none'),
                                  ('010.91','PRIMARY TB NOS-NO EXAM','none'),
                                  ('010.92','PRIMARY TB NOS-EXAM UNKN','none'),
                                  ('010.93','PRIMARY TB NOS-MICRO DX','none'),
                                  ('010.94','PRIMARY TB NOS-CULT DX','none'),
                                  ('010.95','PRIMARY TB NOS-HISTO DX','none'),
                                  ('010.96','PRIMARY TB NOS-OTH TEST','none'),
                                  ('011.00','TB LUNG INFILTR-UNSPEC','none'),
                                  ('011.01','TB LUNG INFILTR-NO EXAM','none'),
                                  ('011.02','TB LUNG INFILTR-EXM UNKN','none'),
                                  ('011.03','TB LUNG INFILTR-MICRO DX','none'),
                                  ('011.04','TB LUNG INFILTR-CULT DX','none'),
                                  ('011.05','TB LUNG INFILTR-HISTO DX','none'),
                                  ('011.06','TB LUNG INFILTR-OTH TEST','none'),
                                  ('011.10','TB LUNG NODULAR-UNSPEC','none'),
                                  ('011.11','TB LUNG NODULAR-NO EXAM','none'),
                                  ('011.12','TB LUNG NODUL-EXAM UNKN','none'),
                                  ('011.13','TB LUNG NODULAR-MICRO DX','none'),
                                  ('011.14','TB LUNG NODULAR-CULT DX','none'),
                                  ('011.15','TB LUNG NODULAR-HISTO DX','none'),
                                  ('011.16','TB LUNG NODULAR-OTH TEST','none'),
                                  ('011.20','TB LUNG W CAVITY-UNSPEC','none'),
                                  ('011.21','TB LUNG W CAVITY-NO EXAM','none'),
                                  ('011.22','TB LUNG CAVITY-EXAM UNKN','none'),
                                  ('011.23','TB LUNG W CAVIT-MICRO DX','none'),
                                  ('011.24','TB LUNG W CAVITY-CULT DX','none'),
                                  ('011.25','TB LUNG W CAVIT-HISTO DX','none'),
                                  ('011.26','TB LUNG W CAVIT-OTH TEST','none'),
                                  ('011.30','TB OF BRONCHUS-UNSPEC','none'),
                                  ('011.31','TB OF BRONCHUS-NO EXAM','none'),
                                  ('011.32','TB OF BRONCHUS-EXAM UNKN','none'),
                                  ('011.33','TB OF BRONCHUS-MICRO DX','none'),
                                  ('011.34','TB OF BRONCHUS-CULT DX','none'),
                                  ('011.35','TB OF BRONCHUS-HISTO DX','none'),
                                  ('011.36','TB OF BRONCHUS-OTH TEST','none'),
                                  ('011.40','TB LUNG FIBROSIS-UNSPEC','none'),
                                  ('011.41','TB LUNG FIBROSIS-NO EXAM','none'),
                                  ('011.42','TB LUNG FIBROS-EXAM UNKN','none'),
                                  ('011.43','TB LUNG FIBROS-MICRO DX','none'),
                                  ('011.44','TB LUNG FIBROSIS-CULT DX','none'),
                                  ('011.45','TB LUNG FIBROS-HISTO DX','none'),
                                  ('011.46','TB LUNG FIBROS-OTH TEST','none'),
                                  ('011.50','TB BRONCHIECTASIS-UNSPEC','none'),
                                  ('011.51','TB BRONCHIECT-NO EXAM','none'),
                                  ('011.52','TB BRONCHIECT-EXAM UNKN','none'),
                                  ('011.53','TB BRONCHIECT-MICRO DX','none'),
                                  ('011.54','TB BRONCHIECT-CULT DX','none'),
                                  ('011.55','TB BRONCHIECT-HISTO DX','none'),
                                  ('011.56','TB BRONCHIECT-OTH TEST','none'),
                                  ('011.60','TB PNEUMONIA-UNSPEC','none'),
                                  ('011.61','TB PNEUMONIA-NO EXAM','none'),
                                  ('011.62','TB PNEUMONIA-EXAM UNKN','none'),
                                  ('011.63','TB PNEUMONIA-MICRO DX','none'),
                                  ('011.64','TB PNEUMONIA-CULT DX','none'),
                                  ('011.65','TB PNEUMONIA-HISTO DX','none'),
                                  ('011.66','TB PNEUMONIA-OTH TEST','none'),
                                  ('011.70','TB PNEUMOTHORAX-UNSPEC','none'),
                                  ('011.71','TB PNEUMOTHORAX-NO EXAM','none'),
                                  ('011.72','TB PNEUMOTHORX-EXAM UNKN','none'),
                                  ('011.73','TB PNEUMOTHORAX-MICRO DX','none'),
                                  ('011.74','TB PNEUMOTHORAX-CULT DX','none'),
                                  ('011.75','TB PNEUMOTHORAX-HISTO DX','none'),
                                  ('011.76','TB PNEUMOTHORAX-OTH TEST','none'),
                                  ('011.80','PULMONARY TB NEC-UNSPEC','none'),
                                  ('011.81','PULMONARY TB NEC-NO EXAM','none'),
                                  ('011.82','PULMON TB NEC-EXAM UNKN','none'),
                                  ('011.83','PULMON TB NEC-MICRO DX','none'),
                                  ('011.84','PULMON TB NEC-CULT DX','none'),
                                  ('011.85','PULMON TB NEC-HISTO DX','none'),
                                  ('011.86','PULMON TB NEC-OTH TEST','none'),
                                  ('011.90','PULMONARY TB NOS-UNSPEC','none'),
                                  ('011.91','PULMONARY TB NOS-NO EXAM','none'),
                                  ('011.92','PULMON TB NOS-EXAM UNKN','none'),
                                  ('011.93','PULMON TB NOS-MICRO DX','none'),
                                  ('011.94','PULMON TB NOS-CULT DX','none'),
                                  ('011.95','PULMON TB NOS-HISTO DX','none'),
                                  ('011.96','PULMON TB NOS-OTH TEST','none'),
                                  ('012.00','TB PLEURISY-UNSPEC','none'),
                                  ('012.01','TB PLEURISY-NO EXAM','none'),
                                  ('012.02','TB PLEURISY-EXAM UNKN','none'),
                                  ('012.03','TB PLEURISY-MICRO DX','none'),
                                  ('012.04','TB PLEURISY-CULT DX','none'),
                                  ('012.05','TB PLEURISY-HISTOLOG DX','none'),
                                  ('012.06','TB PLEURISY-OTH TEST','none'),
                                  ('012.10','TB THORACIC NODES-UNSPEC','none'),
                                  ('012.11','TB THORAX NODE-NO EXAM','none'),
                                  ('012.12','TB THORAX NODE-EXAM UNKN','none'),
                                  ('012.13','TB THORAX NODE-MICRO DX','none'),
                                  ('012.14','TB THORAX NODE-CULT DX','none'),
                                  ('012.15','TB THORAX NODE-HISTO DX','none'),
                                  ('012.16','TB THORAX NODE-OTH TEST','none'),
                                  ('012.20','ISOL TRACHEAL TB-UNSPEC','none'),
                                  ('012.21','ISOL TRACHEAL TB-NO EXAM','none'),
                                  ('012.22','ISOL TRACH TB-EXAM UNKN','none'),
                                  ('012.23','ISOLAT TRACH TB-MICRO DX','none'),
                                  ('012.24','ISOL TRACHEAL TB-CULT DX','none'),
                                  ('012.25','ISOLAT TRACH TB-HISTO DX','none'),
                                  ('012.26','ISOLAT TRACH TB-OTH TEST','none'),
                                  ('012.30','TB LARYNGITIS-UNSPEC','none'),
                                  ('012.31','TB LARYNGITIS-NO EXAM','none'),
                                  ('012.32','TB LARYNGITIS-EXAM UNKN','none'),
                                  ('012.33','TB LARYNGITIS-MICRO DX','none'),
                                  ('012.34','TB LARYNGITIS-CULT DX','none'),
                                  ('012.35','TB LARYNGITIS-HISTO DX','none'),
                                  ('012.36','TB LARYNGITIS-OTH TEST','none'),
                                  ('012.80','RESP TB NEC-UNSPEC','none'),
                                  ('012.81','RESP TB NEC-NO EXAM','none'),
                                  ('012.82','RESP TB NEC-EXAM UNKN','none'),
                                  ('012.83','RESP TB NEC-MICRO DX','none'),
                                  ('012.84','RESP TB NEC-CULT DX','none'),
                                  ('012.85','RESP TB NEC-HISTO DX','none'),
                                  ('012.86','RESP TB NEC-OTH TEST','none'),
                                  ('013.00','TB MENINGITIS-UNSPEC','none'),
                                  ('013.01','TB MENINGITIS-NO EXAM','none'),
                                  ('013.02','TB MENINGITIS-EXAM UNKN','none'),
                                  ('013.03','TB MENINGITIS-MICRO DX','none'),
                                  ('013.04','TB MENINGITIS-CULT DX','none'),
                                  ('013.05','TB MENINGITIS-HISTO DX','none'),
                                  ('013.06','TB MENINGITIS-OTH TEST','none'),
                                  ('013.10','TUBRCLMA MENINGES-UNSPEC','none'),
                                  ('013.11','TUBRCLMA MENING-NO EXAM','none'),
                                  ('013.12','TUBRCLMA MENIN-EXAM UNKN','none'),
                                  ('013.13','TUBRCLMA MENING-MICRO DX','none'),
                                  ('013.14','TUBRCLMA MENING-CULT DX','none'),
                                  ('013.15','TUBRCLMA MENING-HISTO DX','none'),
                                  ('013.16','TUBRCLMA MENING-OTH TEST','none'),
                                  ('013.20','TUBERCULOMA BRAIN-UNSPEC','none'),
                                  ('013.21','TUBRCLOMA BRAIN-NO EXAM','none'),
                                  ('013.22','TUBRCLMA BRAIN-EXAM UNKN','none'),
                                  ('013.23','TUBRCLOMA BRAIN-MICRO DX','none'),
                                  ('013.24','TUBRCLOMA BRAIN-CULT DX','none'),
                                  ('013.25','TUBRCLOMA BRAIN-HISTO DX','none'),
                                  ('013.26','TUBRCLOMA BRAIN-OTH TEST','none'),
                                  ('013.30','TB BRAIN ABSCESS-UNSPEC','none'),
                                  ('013.31','TB BRAIN ABSCESS-NO EXAM','none'),
                                  ('013.32','TB BRAIN ABSC-EXAM UNKN','none'),
                                  ('013.33','TB BRAIN ABSC-MICRO DX','none'),
                                  ('013.34','TB BRAIN ABSCESS-CULT DX','none'),
                                  ('013.35','TB BRAIN ABSC-HISTO DX','none'),
                                  ('013.36','TB BRAIN ABSC-OTH TEST','none'),
                                  ('013.40','TUBRCLMA SP CORD-UNSPEC','none'),
                                  ('013.41','TUBRCLMA SP CORD-NO EXAM','none'),
                                  ('013.42','TUBRCLMA SP CD-EXAM UNKN','none'),
                                  ('013.43','TUBRCLMA SP CRD-MICRO DX','none'),
                                  ('013.44','TUBRCLMA SP CORD-CULT DX','none'),
                                  ('013.45','TUBRCLMA SP CRD-HISTO DX','none'),
                                  ('013.46','TUBRCLMA SP CRD-OTH TEST','none'),
                                  ('013.50','TB SP CRD ABSCESS-UNSPEC','none'),
                                  ('013.51','TB SP CRD ABSC-NO EXAM','none'),
                                  ('013.52','TB SP CRD ABSC-EXAM UNKN','none'),
                                  ('013.53','TB SP CRD ABSC-MICRO DX','none'),
                                  ('013.54','TB SP CRD ABSC-CULT DX','none'),
                                  ('013.55','TB SP CRD ABSC-HISTO DX','none'),
                                  ('013.56','TB SP CRD ABSC-OTH TEST','none'),
                                  ('013.60','TB ENCEPHALITIS-UNSPEC','none'),
                                  ('013.61','TB ENCEPHALITIS-NO EXAM','none'),
                                  ('013.62','TB ENCEPHALIT-EXAM UNKN','none'),
                                  ('013.63','TB ENCEPHALITIS-MICRO DX','none'),
                                  ('013.64','TB ENCEPHALITIS-CULT DX','none'),
                                  ('013.65','TB ENCEPHALITIS-HISTO DX','none'),
                                  ('013.66','TB ENCEPHALITIS-OTH TEST','none'),
                                  ('013.80','CNS TB NEC-UNSPEC','none'),
                                  ('013.81','CNS TB NEC-NO EXAM','none'),
                                  ('013.82','CNS TB NEC-EXAM UNKN','none'),
                                  ('013.83','CNS TB NEC-MICRO DX','none'),
                                  ('013.84','CNS TB NEC-CULT DX','none'),
                                  ('013.85','CNS TB NEC-HISTO DX','none'),
                                  ('013.86','CNS TB NEC-OTH TEST','none'),
                                  ('013.90','CNS TB NOS-UNSPEC','none'),
                                  ('013.91','CNS TB NOS-NO EXAM','none'),
                                  ('013.92','CNS TB NOS-EXAM UNKN','none'),
                                  ('013.93','CNS TB NOS-MICRO DX','none'),
                                  ('013.94','CNS TB NOS-CULT DX','none'),
                                  ('013.95','CNS TB NOS-HISTO DX','none'),
                                  ('013.96','CNS TB NOS-OTH TEST','none'),
                                  ('014.00','TB PERITONITIS-UNSPEC','none'),
                                  ('014.01','TB PERITONITIS-NO EXAM','none'),
                                  ('014.02','TB PERITONITIS-EXAM UNKN','none'),
                                  ('014.03','TB PERITONITIS-MICRO DX','none'),
                                  ('014.04','TB PERITONITIS-CULT DX','none'),
                                  ('014.05','TB PERITONITIS-HISTO DX','none'),
                                  ('014.06','TB PERITONITIS-OTH TEST','none'),
                                  ('014.80','INTESTINAL TB NEC-UNSPEC','none'),
                                  ('014.81','INTESTIN TB NEC-NO EXAM','none'),
                                  ('014.82','INTEST TB NEC-EXAM UNKN','none'),
                                  ('014.83','INTESTIN TB NEC-MICRO DX','none'),
                                  ('014.84','INTESTIN TB NEC-CULT DX','none'),
                                  ('014.85','INTESTIN TB NEC-HISTO DX','none'),
                                  ('014.86','INTESTIN TB NEC-OTH TEST','none'),
                                  ('015.00','TB OF VERTEBRA-UNSPEC','none'),
                                  ('015.01','TB OF VERTEBRA-NO EXAM','none'),
                                  ('015.02','TB OF VERTEBRA-EXAM UNKN','none'),
                                  ('015.03','TB OF VERTEBRA-MICRO DX','none'),
                                  ('015.04','TB OF VERTEBRA-CULT DX','none'),
                                  ('015.05','TB OF VERTEBRA-HISTO DX','none'),
                                  ('015.06','TB OF VERTEBRA-OTH TEST','none'),
                                  ('015.10','TB OF HIP-UNSPEC','none'),
                                  ('015.11','TB OF HIP-NO EXAM','none'),
                                  ('015.12','TB OF HIP-EXAM UNKN','none'),
                                  ('015.13','TB OF HIP-MICRO DX','none'),
                                  ('015.14','TB OF HIP-CULT DX','none'),
                                  ('015.15','TB OF HIP-HISTO DX','none'),
                                  ('015.16','TB OF HIP-OTH TEST','none'),
                                  ('015.20','TB OF KNEE-UNSPEC','none'),
                                  ('015.21','TB OF KNEE-NO EXAM','none'),
                                  ('015.22','TB OF KNEE-EXAM UNKN','none'),
                                  ('015.23','TB OF KNEE-MICRO DX','none'),
                                  ('015.24','TB OF KNEE-CULT DX','none'),
                                  ('015.25','TB OF KNEE-HISTO DX','none'),
                                  ('015.26','TB OF KNEE-OTH TEST','none'),
                                  ('015.50','TB OF LIMB BONES-UNSPEC','none'),
                                  ('015.51','TB LIMB BONES-NO EXAM','none'),
                                  ('015.52','TB LIMB BONES-EXAM UNKN','none'),
                                  ('015.53','TB LIMB BONES-MICRO DX','none'),
                                  ('015.54','TB LIMB BONES-CULT DX','none'),
                                  ('015.55','TB LIMB BONES-HISTO DX','none'),
                                  ('015.56','TB LIMB BONES-OTH TEST','none'),
                                  ('015.60','TB OF MASTOID-UNSPEC','none'),
                                  ('015.61','TB OF MASTOID-NO EXAM','none'),
                                  ('015.62','TB OF MASTOID-EXAM UNKN','none'),
                                  ('015.63','TB OF MASTOID-MICRO DX','none'),
                                  ('015.64','TB OF MASTOID-CULT DX','none'),
                                  ('015.65','TB OF MASTOID-HISTO DX','none'),
                                  ('015.66','TB OF MASTOID-OTH TEST','none'),
                                  ('015.70','TB OF BONE NEC-UNSPEC','none'),
                                  ('015.71','TB OF BONE NEC-NO EXAM','none'),
                                  ('015.72','TB OF BONE NEC-EXAM UNKN','none'),
                                  ('015.73','TB OF BONE NEC-MICRO DX','none'),
                                  ('015.74','TB OF BONE NEC-CULT DX','none'),
                                  ('015.75','TB OF BONE NEC-HISTO DX','none'),
                                  ('015.76','TB OF BONE NEC-OTH TEST','none'),
                                  ('015.80','TB OF JOINT NEC-UNSPEC','none'),
                                  ('015.81','TB OF JOINT NEC-NO EXAM','none'),
                                  ('015.82','TB JOINT NEC-EXAM UNKN','none'),
                                  ('015.83','TB OF JOINT NEC-MICRO DX','none'),
                                  ('015.84','TB OF JOINT NEC-CULT DX','none'),
                                  ('015.85','TB OF JOINT NEC-HISTO DX','none'),
                                  ('015.86','TB OF JOINT NEC-OTH TEST','none'),
                                  ('015.90','TB BONE/JOINT NOS-UNSPEC','none'),
                                  ('015.91','TB BONE/JT NOS-NO EXAM','none'),
                                  ('015.92','TB BONE/JT NOS-EXAM UNKN','none'),
                                  ('015.93','TB BONE/JT NOS-MICRO DX','none'),
                                  ('015.94','TB BONE/JT NOS-CULT DX','none'),
                                  ('015.95','TB BONE/JT NOS-HISTO DX','none'),
                                  ('015.96','TB BONE/JT NOS-OTH TEST','none'),
                                  ('016.00','TB OF KIDNEY-UNSPEC','none'),
                                  ('016.01','TB OF KIDNEY-NO EXAM','none'),
                                  ('016.02','TB OF KIDNEY-EXAM UNKN','none'),
                                  ('016.03','TB OF KIDNEY-MICRO DX','none'),
                                  ('016.04','TB OF KIDNEY-CULT DX','none'),
                                  ('016.05','TB OF KIDNEY-HISTO DX','none'),
                                  ('016.06','TB OF KIDNEY-OTH TEST','none'),
                                  ('016.10','TB OF BLADDER-UNSPEC','none'),
                                  ('016.11','TB OF BLADDER-NO EXAM','none'),
                                  ('016.12','TB OF BLADDER-EXAM UNKN','none'),
                                  ('016.13','TB OF BLADDER-MICRO DX','none'),
                                  ('016.14','TB OF BLADDER-CULT DX','none'),
                                  ('016.15','TB OF BLADDER-HISTO DX','none'),
                                  ('016.16','TB OF BLADDER-OTH TEST','none'),
                                  ('016.20','TB OF URETER-UNSPEC','none'),
                                  ('016.21','TB OF URETER-NO EXAM','none'),
                                  ('016.22','TB OF URETER-EXAM UNKN','none'),
                                  ('016.23','TB OF URETER-MICRO DX','none'),
                                  ('016.24','TB OF URETER-CULT DX','none'),
                                  ('016.25','TB OF URETER-HISTO DX','none'),
                                  ('016.26','TB OF URETER-OTH TEST','none'),
                                  ('016.30','TB URINARY NEC-UNSPEC','none'),
                                  ('016.31','TB URINARY NEC-NO EXAM','none'),
                                  ('016.32','TB URINARY NEC-EXAM UNKN','none'),
                                  ('016.33','TB URINARY NEC-MICRO DX','none'),
                                  ('016.34','TB URINARY NEC-CULT DX','none'),
                                  ('016.35','TB URINARY NEC-HISTO DX','none'),
                                  ('016.36','TB URINARY NEC-OTH TEST','none'),
                                  ('016.40','TB EPIDIDYMIS-UNSPEC','none'),
                                  ('016.41','TB EPIDIDYMIS-NO EXAM','none'),
                                  ('016.42','TB EPIDIDYMIS-EXAM UNKN','none'),
                                  ('016.43','TB EPIDIDYMIS-MICRO DX','none'),
                                  ('016.44','TB EPIDIDYMIS-CULT DX','none'),
                                  ('016.45','TB EPIDIDYMIS-HISTO DX','none'),
                                  ('016.46','TB EPIDIDYMIS-OTH TEST','none'),
                                  ('016.50','TB MALE GENIT NEC-UNSPEC','none'),
                                  ('016.51','TB MALE GEN NEC-NO EXAM','none'),
                                  ('016.52','TB MALE GEN NEC-EX UNKN','none'),
                                  ('016.53','TB MALE GEN NEC-MICRO DX','none'),
                                  ('016.54','TB MALE GEN NEC-CULT DX','none'),
                                  ('016.55','TB MALE GEN NEC-HISTO DX','none'),
                                  ('016.56','TB MALE GEN NEC-OTH TEST','none'),
                                  ('016.60','TB OVARY & TUBE-UNSPEC','none'),
                                  ('016.61','TB OVARY & TUBE-NO EXAM','none'),
                                  ('016.62','TB OVARY/TUBE-EXAM UNKN','none'),
                                  ('016.63','TB OVARY & TUBE-MICRO DX','none'),
                                  ('016.64','TB OVARY & TUBE-CULT DX','none'),
                                  ('016.65','TB OVARY & TUBE-HISTO DX','none'),
                                  ('016.66','TB OVARY & TUBE-OTH TEST','none'),
                                  ('016.70','TB FEMALE GEN NEC-UNSPEC','none'),
                                  ('016.71','TB FEM GEN NEC-NO EXAM','none'),
                                  ('016.72','TB FEM GEN NEC-EXAM UNKN','none'),
                                  ('016.73','TB FEM GEN NEC-MICRO DX','none'),
                                  ('016.74','TB FEM GEN NEC-CULT DX','none'),
                                  ('016.75','TB FEM GEN NEC-HISTO DX','none'),
                                  ('016.76','TB FEM GEN NEC-OTH TEST','none'),
                                  ('016.90','GU TB NOS-UNSPEC','none'),
                                  ('016.91','GU TB NOS-NO EXAM','none'),
                                  ('016.92','GU TB NOS-EXAM UNKN','none'),
                                  ('016.93','GU TB NOS-MICRO DX','none'),
                                  ('016.94','GU TB NOS-CULT DX','none'),
                                  ('016.95','GU TB NOS-HISTO DX','none'),
                                  ('016.96','GU TB NOS-OTH TEST','none'),
                                  ('017.00','TB SKIN/SUBCUTAN-UNSPEC','none'),
                                  ('017.01','TB SKIN/SUBCUT-NO EXAM','none'),
                                  ('017.02','TB SKIN/SUBCUT-EXAM UNKN','none'),
                                  ('017.03','TB SKIN/SUBCUT-MICRO DX','none'),
                                  ('017.04','TB SKIN/SUBCUT-CULT DX','none'),
                                  ('017.05','TB SKIN/SUBCUT-HISTO DX','none'),
                                  ('017.06','TB SKIN/SUBCUT-OTH TEST','none'),
                                  ('017.10','ERYTHEMA NODOS TB-UNSPEC','none'),
                                  ('017.11','ERYTHEM NODOS TB-NO EXAM','none'),
                                  ('017.12','ERYTHEM NOD TB-EXAM UNKN','none'),
                                  ('017.13','ERYTHEM NOD TB-MICRO DX','none'),
                                  ('017.14','ERYTHEM NODOS TB-CULT DX','none'),
                                  ('017.15','ERYTHEM NOD TB-HISTO DX','none'),
                                  ('017.16','ERYTHEM NOD TB-OTH TEST','none'),
                                  ('017.20','TB PERIPH LYMPH-UNSPEC','none'),
                                  ('017.21','TB PERIPH LYMPH-NO EXAM','none'),
                                  ('017.22','TB PERIPH LYMPH-EXAM UNK','none'),
                                  ('017.23','TB PERIPH LYMPH-MICRO DX','none'),
                                  ('017.24','TB PERIPH LYMPH-CULT DX','none'),
                                  ('017.25','TB PERIPH LYMPH-HISTO DX','none'),
                                  ('017.26','TB PERIPH LYMPH-OTH TEST','none'),
                                  ('017.30','TB OF EYE-UNSPEC','none'),
                                  ('017.31','TB OF EYE-NO EXAM','none'),
                                  ('017.32','TB OF EYE-EXAM UNKN','none'),
                                  ('017.33','TB OF EYE-MICRO DX','none'),
                                  ('017.34','TB OF EYE-CULT DX','none'),
                                  ('017.35','TB OF EYE-HISTO DX','none'),
                                  ('017.36','TB OF EYE-OTH TEST','none'),
                                  ('017.40','TB OF EAR-UNSPEC','none'),
                                  ('017.41','TB OF EAR-NO EXAM','none'),
                                  ('017.42','TB OF EAR-EXAM UNKN','none'),
                                  ('017.43','TB OF EAR-MICRO DX','none'),
                                  ('017.44','TB OF EAR-CULT DX','none'),
                                  ('017.45','TB OF EAR-HISTO DX','none'),
                                  ('017.46','TB OF EAR-OTH TEST','none'),
                                  ('017.50','TB OF THYROID-UNSPEC','none'),
                                  ('017.51','TB OF THYROID-NO EXAM','none'),
                                  ('017.52','TB OF THYROID-EXAM UNKN','none'),
                                  ('017.53','TB OF THYROID-MICRO DX','none'),
                                  ('017.54','TB OF THYROID-CULT DX','none'),
                                  ('017.55','TB OF THYROID-HISTO DX','none'),
                                  ('017.56','TB OF THYROID-OTH TEST','none'),
                                  ('017.60','TB OF ADRENAL-UNSPEC','none'),
                                  ('017.61','TB OF ADRENAL-NO EXAM','none'),
                                  ('017.62','TB OF ADRENAL-EXAM UNKN','none'),
                                  ('017.63','TB OF ADRENAL-MICRO DX','none'),
                                  ('017.64','TB OF ADRENAL-CULT DX','none'),
                                  ('017.65','TB OF ADRENAL-HISTO DX','none'),
                                  ('017.66','TB OF ADRENAL-OTH TEST','none'),
                                  ('017.70','TB OF SPLEEN-UNSPEC','none'),
                                  ('017.71','TB OF SPLEEN-NO EXAM','none'),
                                  ('017.72','TB OF SPLEEN-EXAM UNKN','none'),
                                  ('017.73','TB OF SPLEEN-MICRO DX','none'),
                                  ('017.74','TB OF SPLEEN-CULT DX','none'),
                                  ('017.75','TB OF SPLEEN-HISTO DX','none'),
                                  ('017.76','TB OF SPLEEN-OTH TEST','none'),
                                  ('017.80','TB ESOPHAGUS-UNSPEC','none'),
                                  ('017.81','TB ESOPHAGUS-NO EXAM','none'),
                                  ('017.82','TB ESOPHAGUS-EXAM UNKN','none'),
                                  ('017.83','TB ESOPHAGUS-MICRO DX','none'),
                                  ('017.84','TB ESOPHAGUS-CULT DX','none'),
                                  ('017.85','TB ESOPHAGUS-HISTO DX','none'),
                                  ('017.86','TB ESOPHAGUS-OTH TEST','none'),
                                  ('017.90','TB OF ORGAN NEC-UNSPEC','none'),
                                  ('017.91','TB OF ORGAN NEC-NO EXAM','none'),
                                  ('017.92','TB ORGAN NEC-EXAM UNKN','none'),
                                  ('017.93','TB OF ORGAN NEC-MICRO DX','none'),
                                  ('017.94','TB OF ORGAN NEC-CULT DX','none'),
                                  ('017.95','TB OF ORGAN NEC-HISTO DX','none'),
                                  ('017.96','TB OF ORGAN NEC-OTH TEST','none'),
                                  ('018.00','ACUTE MILIARY TB-UNSPEC','none'),
                                  ('018.01','ACUTE MILIARY TB-NO EXAM','none'),
                                  ('018.02','AC MILIARY TB-EXAM UNKN','none'),
                                  ('018.03','AC MILIARY TB-MICRO DX','none'),
                                  ('018.04','ACUTE MILIARY TB-CULT DX','none'),
                                  ('018.05','AC MILIARY TB-HISTO DX','none'),
                                  ('018.06','AC MILIARY TB-OTH TEST','none'),
                                  ('018.80','MILIARY TB NEC-UNSPEC','none'),
                                  ('018.81','MILIARY TB NEC-NO EXAM','none'),
                                  ('018.82','MILIARY TB NEC-EXAM UNKN','none'),
                                  ('018.83','MILIARY TB NEC-MICRO DX','none'),
                                  ('018.84','MILIARY TB NEC-CULT DX','none'),
                                  ('018.85','MILIARY TB NEC-HISTO DX','none'),
                                  ('018.86','MILIARY TB NEC-OTH TEST','none'),
                                  ('018.90','MILIARY TB NOS-UNSPEC','none'),
                                  ('018.91','MILIARY TB NOS-NO EXAM','none'),
                                  ('018.92','MILIARY TB NOS-EXAM UNKN','none'),
                                  ('018.93','MILIARY TB NOS-MICRO DX','none'),
                                  ('018.94','MILIARY TB NOS-CULT DX','none'),
                                  ('018.95','MILIARY TB NOS-HISTO DX','none'),
                                  ('018.96','MILIARY TB NOS-OTH TEST','none'),
                                  ('020.00','BUBONIC PLAGUE','none'),
                                  ('020.10','CELLULOCUTANEOUS PLAGUE','none'),
                                  ('020.20','SEPTICEMIC PLAGUE','none'),
                                  ('020.30','PRIMARY PNEUMONIC PLAGUE','none'),
                                  ('020.40','SECONDARY PNEUMON PLAGUE','none'),
                                  ('020.50','PNEUMONIC PLAGUE NOS','none'),
                                  ('020.80','OTHER TYPES OF PLAGUE','none'),
                                  ('020.90','PLAGUE NOS','none'),
                                  ('021.00','ULCEROGLANDUL TULAREMIA','none'),
                                  ('021.10','ENTERIC TULAREMIA','none'),
                                  ('021.20','PULMONARY TULAREMIA','none'),
                                  ('021.30','OCULOGLANDULAR TULAREMIA','none'),
                                  ('021.80','TULAREMIA NEC','none'),
                                  ('021.90','TULAREMIA NOS','none'),
                                  ('022.00','CUTANEOUS ANTHRAX','none'),
                                  ('022.10','PULMONARY ANTHRAX','none'),
                                  ('022.20','GASTROINTESTINAL ANTHRAX','none'),
                                  ('022.30','ANTHRAX SEPTICEMIA','none'),
                                  ('022.80','OTHER ANTHRAX MANIFEST','none'),
                                  ('022.90','ANTHRAX NOS','none'),
                                  ('023.00','BRUCELLA MELITENSIS','none'),
                                  ('023.10','BRUCELLA ABORTUS','none'),
                                  ('023.20','BRUCELLA SUIS','none'),
                                  ('023.30','BRUCELLA CANIS','none'),
                                  ('023.80','BRUCELLOSIS NEC','none'),
                                  ('023.90','BRUCELLOSIS NOS','none'),
                                  ('024.00','GLANDERS','none'),
                                  ('025.00','MELIOIDOSIS','none'),
                                  ('026.00','SPIRILLARY FEVER','none'),
                                  ('026.10','STREPTOBACILLARY FEVER','none'),
                                  ('026.90','RAT-BITE FEVER NOS','none'),
                                  ('027.00','LISTERIOSIS','none'),
                                  ('027.10','ERYSIPELOTHRIX INFECTION','none'),
                                  ('027.20','PASTEURELLOSIS','none'),
                                  ('027.80','ZOONOTIC BACT DIS NEC','none'),
                                  ('027.90','ZOONOTIC BACT DIS NOS','none'),
                                  ('030.00','LEPROMATOUS LEPROSY','none'),
                                  ('030.10','TUBERCULOID LEPROSY','none'),
                                  ('030.20','INDETERMINATE LEPROSY','none'),
                                  ('030.30','BORDERLINE LEPROSY','none'),
                                  ('030.80','LEPROSY NEC','none'),
                                  ('030.90','LEPROSY NOS','none'),
                                  ('031.00','PULMONARY MYCOBACTERIA','none'),
                                  ('031.10','CUTANEOUS MYCOBACTERIA','none'),
                                  ('031.20','DMAC BACTEREMIA','none'),
                                  ('031.80','MYCOBACTERIAL DIS NEC','none'),
                                  ('031.90','MYCOBACTERIAL DIS NOS','none'),
                                  ('032.00','FAUCIAL DIPHTHERIA','none'),
                                  ('032.10','NASOPHARYNX DIPHTHERIA','none'),
                                  ('032.20','ANT NASAL DIPHTHERIA','none'),
                                  ('032.30','LARYNGEAL DIPHTHERIA','none'),
                                  ('032.81','CONJUNCTIVAL DIPHTHERIA','none'),
                                  ('032.82','DIPHTHERITIC MYOCARDITIS','none'),
                                  ('032.83','DIPHTHERITIC PERITONITIS','none'),
                                  ('032.84','DIPHTHERITIC CYSTITIS','none'),
                                  ('032.85','CUTANEOUS DIPHTHERIA','none'),
                                  ('032.89','DIPHTHERIA NEC','none'),
                                  ('032.90','DIPHTHERIA NOS','none'),
                                  ('033.00','BORDETELLA PERTUSSIS','none'),
                                  ('033.10','BORDETELLA PARAPERTUSSIS','none'),
                                  ('033.80','WHOOPING COUGH NEC','none'),
                                  ('033.90','WHOOPING COUGH NOS','none'),
                                  ('034.00','STREP SORE THROAT','none'),
                                  ('034.10','SCARLET FEVER','none'),
                                  ('035.00','ERYSIPELAS','none'),
                                  ('036.00','MENINGOCOCCAL MENINGITIS','none'),
                                  ('036.10','MENINGOCOCC ENCEPHALITIS','none'),
                                  ('036.20','MENINGOCOCCEMIA','none'),
                                  ('036.30','MENINGOCOCC ADRENAL SYND','none'),
                                  ('036.40','MENINGOCOCC CARDITIS NOS','none'),
                                  ('036.41','MENINGOCOCC PERICARDITIS','none'),
                                  ('036.42','MENINGOCOCC ENDOCARDITIS','none'),
                                  ('036.43','MENINGOCOCC MYOCARDITIS','none'),
                                  ('036.81','MENINGOCOCC OPTIC NEURIT','none'),
                                  ('036.82','MENINGOCOCC ARTHROPATHY','none'),
                                  ('036.89','MENINGOCOCCAL INFECT NEC','none'),
                                  ('036.90','MENINGOCOCCAL INFECT NOS','none'),
                                  ('037.00','TETANUS','none'),
                                  ('038.00','STREPTOCOCCAL SEPTICEMIA','none'),
                                  ('038.10','STAPHYLCOCC SEPTICEM NOS','none'),
                                  ('038.11','STAPH AUREUS SEPTICEMIA','none'),
                                  ('038.19','STAPHYLCOCC SEPTICEM NEC','none'),
                                  ('038.20','PNEUMOCOCCAL SEPTICEMIA','none'),
                                  ('038.30','ANAEROBIC SEPTICEMIA','none'),
                                  ('038.40','GRAM-NEG SEPTICEMIA NOS','none'),
                                  ('038.41','H. INFLUENAE SEPTICEMIA','none'),
                                  ('038.42','E COLI SEPTICEMIA','none'),
                                  ('038.43','PSEUDOMONAS SEPTICEMIA','none'),
                                  ('038.44','SERRATIA SEPTICEMIA','none'),
                                  ('038.49','GRAM-NEG SEPTICEMIA NEC','none'),
                                  ('038.80','SEPTICEMIA NEC','none'),
                                  ('038.90','SEPTICEMIA NOS','none'),
                                  ('039.00','CUTANEOUS ACTINOMYCOSIS','none'),
                                  ('039.10','PULMONARY ACTINOMYCOSIS','none'),
                                  ('039.20','ABDOMINAL ACTINOMYCOSIS','none'),
                                  ('039.30','CERVICOFAC ACTINOMYCOSIS','none'),
                                  ('039.40','MADURA FOOT','none'),
                                  ('039.80','ACTINOMYCOSIS NEC','none'),
                                  ('039.90','ACTINOMYCOSIS NOS','none'),
                                  ('040.00','GAS GANGRENE','none'),
                                  ('040.10','RHINOSCLEROMA','none'),
                                  ('040.20','WHIPPLE''S DISEASE','none'),
                                  ('040.30','NECROBACILLOSIS','none'),
                                  ('040.81','TROPICAL PYOMYOSITIS','none'),
                                  ('040.82','TOXIC SHOCK SYNDROME','none'),
                                  ('040.89','BACTERIAL DISEASES NEC','none'),
                                  ('041.00','STREPTOCOCCUS UNSPECF','none'),
                                  ('041.01','STREPTOCOCCUS GROUP A','none'),
                                  ('041.02','STREPTOCOCCUS GROUP B','none'),
                                  ('041.03','STREPTOCOCCUS GROUP C','none'),
                                  ('041.04','ENTEROCOCCUS GROUP D','none'),
                                  ('041.05','STREPTOCOCCUS GROUP G','none'),
                                  ('041.09','OTHER STREPTOCOCCUS','none'),
                                  ('041.10','STAPHYLOCOCCUS UNSPCFIED','none'),
                                  ('041.11','STAPHYLOCOCCUS AUREUS','none'),
                                  ('041.19','OTHER STAPHYLOCOCCUS','none'),
                                  ('041.20','PNEUMOCOCCUS INFECT NOS','none'),
                                  ('041.30','KLEBSIELLA INFECT NOS','none'),
                                  ('041.40','E. COLI INFECT NOS','none'),
                                  ('041.50','H. INFLUENZAE INFECT NOS','none'),
                                  ('041.60','PROTEUS INFECTION NOS','none'),
                                  ('041.70','PSEUDOMONAS INFECT NOS','none'),
                                  ('041.81','MYCOPLASMA','none'),
                                  ('041.82','BACTEROIDES FRAGILIS','none'),
                                  ('041.83','CLOSTRIDIUM PERFRINGENS','none'),
                                  ('041.84','OTHER ANAEROBES','none'),
                                  ('041.85','OTH GRAM NEGATV BACTERIA','none'),
                                  ('041.86','HELICOBACTER PYLORI','none'),
                                  ('041.89','OTH SPECF BACTERIA','none'),
                                  ('041.90','BACTERIAL INFECTION NOS','none'),
                                  ('042.00','HUMAN IMMUNO VIRUS DIS','none'),
                                  ('045.00','AC BULBAR POLIO-TYPE NOS','none'),
                                  ('045.01','AC BULBAR POLIO-TYPE 1','none'),
                                  ('045.02','AC BULBAR POLIO-TYPE 2','none'),
                                  ('045.03','AC BULBAR POLIO-TYPE 3','none'),
                                  ('045.10','PARAL POLIO NEC-TYPE NOS','none'),
                                  ('045.11','PARAL POLIO NEC-TYPE 1','none'),
                                  ('045.12','PARAL POLIO NEC-TYPE 2','none'),
                                  ('045.13','PARAL POLIO NEC-TYPE 3','none'),
                                  ('045.20','NONPARALY POLIO-TYPE NOS','none'),
                                  ('045.21','NONPARALYT POLIO-TYPE 1','none'),
                                  ('045.22','NONPARALYT POLIO-TYPE 2','none'),
                                  ('045.23','NONPARALYT POLIO-TYPE 3','none'),
                                  ('045.90','AC POLIO NOS-TYPE NOS','none'),
                                  ('045.91','AC POLIO NOS-TYPE 1','none'),
                                  ('045.92','AC POLIO NOS-TYPE 2','none'),
                                  ('045.93','AC POLIO NOS-TYPE 3','none'),
                                  ('046.00','KURU','none'),
                                  ('046.10','JAKOB-CREUTZFELDT DIS','none'),
                                  ('046.20','SUBAC SCLEROS PANENCEPH','none'),
                                  ('046.30','PROG MULTIFOC LEUKOENCEP','none'),
                                  ('046.80','CNS SLOW VIRUS INFEC NEC','none'),
                                  ('046.90','CNS SLOW VIRUS INFEC NOS','none'),
                                  ('047.00','COXSACKIE VIRUS MENING','none'),
                                  ('047.10','ECHO VIRUS MENINGITIS','none'),
                                  ('047.80','VIRAL MENINGITIS NEC','none'),
                                  ('047.90','VIRAL MENINGITIS NOS','none'),
                                  ('048.00','OTH ENTEROVIRAL CNS DIS','none'),
                                  ('049.00','LYMPHOCYTIC CHORIOMENING','none'),
                                  ('049.10','ADENOVIRAL MENINGITIS','none'),
                                  ('049.80','VIRAL ENCEPHALITIS NEC','none'),
                                  ('049.90','VIRAL ENCEPHALITIS NOS','none'),
                                  ('050.00','VARIOLA MAJOR','none'),
                                  ('050.10','ALASTRIM','none'),
                                  ('050.20','MODIFIED SMALLPOX','none'),
                                  ('050.90','SMALLPOX NOS','none'),
                                  ('051.00','COWPOX','none'),
                                  ('051.10','PSEUDOCOWPOX','none'),
                                  ('051.20','CONTAGIOUS PUSTULAR DERM','none'),
                                  ('051.90','PARAVACCINIA NOS','none'),
                                  ('052.00','POSTVARICELLA ENCEPHALIT','none'),
                                  ('052.10','VARICELLA PNEUMONITIS','none'),
                                  ('052.70','VARICELLA COMPLICAT NEC','none'),
                                  ('052.80','VARICELLA COMPLICAT NOS','none'),
                                  ('052.90','VARICELLA UNCOMPLICATED','none'),
                                  ('053.00','HERPES ZOSTER MENINGITIS','none'),
                                  ('053.10','H ZOSTER NERV SYST NOS','none'),
                                  ('053.11','GENICULATE HERPES ZOSTER','none'),
                                  ('053.12','POSTHERPES TRIGEM NEURAL','none'),
                                  ('053.13','POSTHERPES POLYNEUROPATH','none'),
                                  ('053.19','H ZOSTER NERV SYST NEC','none'),
                                  ('053.20','HERPES ZOSTER OF EYELID','none'),
                                  ('053.21','H ZOSTER KERATOCONJUNCT','none'),
                                  ('053.22','H ZOSTER IRIDOCYCLITIS','none'),
                                  ('053.29','HERPES ZOSTER OF EYE NEC','none'),
                                  ('053.71','H ZOSTER OTITIS EXTERNA','none'),
                                  ('053.79','H ZOSTER COMPLICATED NEC','none'),
                                  ('053.80','H ZOSTER COMPLICATED NOS','none'),
                                  ('053.90','HERPES ZOSTER NOS','none'),
                                  ('054.00','ECZEMA HERPETICUM','none'),
                                  ('054.10','GENITAL HERPES NOS','none'),
                                  ('054.11','HERPETIC VULVOVAGINITIS','none'),
                                  ('054.12','HERPETIC ULCER OF VULVA','none'),
                                  ('054.13','HERPETIC INFECT OF PENIS','none'),
                                  ('054.19','GENITAL HERPES NEC','none'),
                                  ('054.20','HERPETIC GINGIVOSTOMAT','none'),
                                  ('054.30','HERPETIC ENCEPHALITIS','none'),
                                  ('054.40','HERPES SIMPLEX EYE NOS','none'),
                                  ('054.41','HERPES SIMPLEX OF EYELID','none'),
                                  ('054.42','DENDRITIC KERATITIS','none'),
                                  ('054.43','H SIMPLEX KERATITIS','none'),
                                  ('054.44','H SIMPLEX IRIDOCYCLITIS','none'),
                                  ('054.49','HERPES SIMPLEX EYE NEC','none'),
                                  ('054.50','HERPETIC SEPTICEMIA','none'),
                                  ('054.60','HERPETIC WHITLOW','none'),
                                  ('054.71','VISCERAL HERPES SIMPLEX','none'),
                                  ('054.72','H SIMPLEX MENINGITIS','none'),
                                  ('054.73','H SIMPLEX OTITIS EXTERNA','none'),
                                  ('054.79','H SIMPLEX COMPLICAT NEC','none'),
                                  ('054.80','H SIMPLEX COMPLICAT NOS','none'),
                                  ('054.90','HERPES SIMPLEX NOS','none'),
                                  ('055.00','POSTMEASLES ENCEPHALITIS','none'),
                                  ('055.10','POSTMEASLES PNEUMONIA','none'),
                                  ('055.20','POSTMEASLES OTITIS MEDIA','none'),
                                  ('055.71','MEASLES KERATITIS','none'),
                                  ('055.79','MEASLES COMPLICATION NEC','none'),
                                  ('055.80','MEASLES COMPLICATION NOS','none'),
                                  ('055.90','MEASLES UNCOMPLICATED','none'),
                                  ('056.00','RUBELLA NERVE COMPL NOS','none'),
                                  ('056.01','RUBELLA ENCEPHALITIS','none'),
                                  ('056.09','RUBELLA NERVE COMPL NEC','none'),
                                  ('056.71','ARTHRITIS DUE TO RUBELLA','none'),
                                  ('056.79','RUBELLA COMPLICATION NEC','none'),
                                  ('056.80','RUBELLA COMPLICATION NOS','none'),
                                  ('056.90','RUBELLA UNCOMPLICATED','none'),
                                  ('057.00','ERYTHEMA INFECTIOSUM','none'),
                                  ('057.80','VIRAL EXANTHEMATA NEC','none'),
                                  ('057.90','VIRAL EXANTHEMATA NOS','none'),
                                  ('060.00','SYLVATIC YELLOW FEVER','none'),
                                  ('060.10','URBAN YELLOW FEVER','none'),
                                  ('060.90','YELLOW FEVER NOS','none'),
                                  ('061.00','DENGUE','none'),
                                  ('062.00','JAPANESE ENCEPHALITIS','none'),
                                  ('062.10','WEST EQUINE ENCEPHALITIS','none'),
                                  ('062.20','EAST EQUINE ENCEPHALITIS','none'),
                                  ('062.30','ST LOUIS ENCEPHALITIS','none'),
                                  ('062.40','AUSTRALIAN ENCEPHALITIS','none'),
                                  ('062.50','CALIFORNIA ENCEPHALITIS','none'),
                                  ('062.80','MOSQUIT-BORNE ENCEPH NEC','none'),
                                  ('062.90','MOSQUIT-BORNE ENCEPH NOS','none'),
                                  ('063.00','RUSSIA SPR-SUMMER ENCEPH','none'),
                                  ('063.10','LOUPING ILL','none'),
                                  ('063.20','CENT EUROPE ENCEPHALITIS','none'),
                                  ('063.80','TICK-BORNE ENCEPH NEC','none'),
                                  ('063.90','TICK-BORNE ENCEPH NOS','none'),
                                  ('064.00','VIR ENCEPH ARTHROPOD NEC','none'),
                                  ('065.00','CRIMEAN HEMORRHAGIC FEV','none'),
                                  ('065.10','OMSK HEMORRHAGIC FEVER','none'),
                                  ('065.20','KYASANUR FOREST DISEASE','none'),
                                  ('065.30','TICK-BORNE HEM FEVER NEC','none'),
                                  ('065.40','MOSQUITO-BORNE HEM FEVER','none'),
                                  ('065.80','ARTHROPOD HEM FEVER NEC','none'),
                                  ('065.90','ARTHROPOD HEM FEVER NOS','none'),
                                  ('066.00','PHLEBOTOMUS FEVER','none'),
                                  ('066.10','TICK-BORNE FEVER','none'),
                                  ('066.20','VENEZUELAN EQUINE FEVER','none'),
                                  ('066.30','MOSQUITO-BORNE FEVER NEC','none'),
                                  ('066.40','WEST NILE FEVER NOS','none'),
                                  ('066.41','WEST NILE FEVER W/ENCEPH','none'),
                                  ('066.42','WEST NILE NEURO MAN NEC','none'),
                                  ('066.49','WEST NILE W COMPLIC NEC','none'),
                                  ('066.80','ARTHROPOD VIRUS NEC','none'),
                                  ('066.90','ARTHROPOD VIRUS NOS','none'),
                                  ('070.00','HEPATITIS A WITH COMA','none'),
                                  ('070.10','HEPATITIS A W/O COMA','none'),
                                  ('070.20','HPT B ACTE COMA WO DLTA','none'),
                                  ('070.21','HPT B ACTE COMA W DLTA','none'),
                                  ('070.22','HPT B CHRN COMA WO DLTA','none'),
                                  ('070.23','HPT B CHRN COMA W DLTA','none'),
                                  ('070.30','HPT B ACTE WO CM WO DLTA','none'),
                                  ('070.31','HPT B ACTE WO CM W DLTA','none'),
                                  ('070.32','HPT B CHRN WO CM WO DLTA','none'),
                                  ('070.33','HPT B CHRN WO CM W DLTA','none'),
                                  ('070.41','HPT C ACUTE W HEPAT COMA','none'),
                                  ('070.42','HPT DLT WO B W HPT COMA','none'),
                                  ('070.43','HPT E W HEPAT COMA','none'),
                                  ('070.44','CHRNC HPT C W HEPAT COMA','none'),
                                  ('070.49','OTH VRL HEPAT W HPT COMA','none'),
                                  ('070.51','HPT C ACUTE WO HPAT COMA','none'),
                                  ('070.52','HPT DLT WO B WO HPT COMA','none'),
                                  ('070.53','HPT E WO HEPAT COMA','none'),
                                  ('070.54','CHRNC HPT C WO HPAT COMA','none'),
                                  ('070.59','OTH VRL HPAT WO HPT COMA','none'),
                                  ('070.60','VIRAL HEPAT NOS W COMA','none'),
                                  ('070.70','HPT C W/O HEPAT COMA NOS','none'),
                                  ('070.71','HPT C W HEPATIC COMA NOS','none'),
                                  ('070.90','VIRAL HEPAT NOS W/O COMA','none'),
                                  ('071.00','RABIES','none'),
                                  ('072.00','MUMPS ORCHITIS','none'),
                                  ('072.10','MUMPS MENINGITIS','none'),
                                  ('072.20','MUMPS ENCEPHALITIS','none'),
                                  ('072.30','MUMPS PANCREATITIS','none'),
                                  ('072.71','MUMPS HEPATITIS','none'),
                                  ('072.72','MUMPS POLYNEUROPATHY','none'),
                                  ('072.79','MUMPS COMPLICATION NEC','none'),
                                  ('072.80','MUMPS COMPLICATION NOS','none'),
                                  ('072.90','MUMPS UNCOMPLICATED','none'),
                                  ('073.00','ORNITHOSIS PNEUMONIA','none'),
                                  ('073.70','ORNITHOSIS COMPLICAT NEC','none'),
                                  ('073.80','ORNITHOSIS COMPLICAT NOS','none'),
                                  ('073.90','ORNITHOSIS NOS','none'),
                                  ('074.00','HERPANGINA','none'),
                                  ('074.10','EPIDEMIC PLEURODYNIA','none'),
                                  ('074.20','COXSACKIE CARDITIS NOS','none'),
                                  ('074.21','COXSACKIE PERICARDITIS','none'),
                                  ('074.22','COXSACKIE ENDOCARDITIS','none'),
                                  ('074.23','COXSACKIE MYOCARDITIS','none'),
                                  ('074.30','HAND, FOOT & MOUTH DIS','none'),
                                  ('074.80','COXSACKIE VIRUS NEC','none'),
                                  ('075.00','INFECTIOUS MONONUCLEOSIS','none'),
                                  ('076.00','TRACHOMA, INITIAL STAGE','none'),
                                  ('076.10','TRACHOMA, ACTIVE STAGE','none'),
                                  ('076.90','TRACHOMA NOS','none'),
                                  ('077.00','INCLUSION CONJUNCTIVITIS','none'),
                                  ('077.10','EPIDEM KERATOCONJUNCTIV','none'),
                                  ('077.20','PHARYNGOCONJUNCT FEVER','none'),
                                  ('077.30','ADENOVIRAL CONJUNCT NEC','none'),
                                  ('077.40','EPIDEM HEM CONJUNCTIVIT','none'),
                                  ('077.80','VIRAL CONJUNCTIVITIS NEC','none'),
                                  ('077.98','UNSP DS CONJUC CHLAMYDIA','none'),
                                  ('077.99','UNSP DS CONJUC VIRUSES','none'),
                                  ('078.00','MOLLUSCUM CONTAGIOSUM','none'),
                                  ('078.10','VIRAL WARTS NOS','none'),
                                  ('078.11','CONDYLOMA ACUMINATUM','none'),
                                  ('078.19','OTH SPECFD VIRAL WARTS','none'),
                                  ('078.20','SWEATING FEVER','none'),
                                  ('078.30','CAT-SCRATCH DISEASE','none'),
                                  ('078.40','FOOT & MOUTH DISEASE','none'),
                                  ('078.50','CYTOMEGALOVIRAL DISEASE','none'),
                                  ('078.60','HEM NEPHROSONEPHRITIS','none'),
                                  ('078.70','ARENAVIRAL HEM FEVER','none'),
                                  ('078.81','EPIDEMIC VERTIGO','none'),
                                  ('078.82','EPIDEMIC VOMITING SYND','none'),
                                  ('078.88','OTH SPEC DIS CHLAMYDIAE','none'),
                                  ('078.89','OTH SPEC DIS VIRUSES','none'),
                                  ('079.00','ADENOVIRUS INFECT NOS','none'),
                                  ('079.10','ECHO VIRUS INFECT NOS','none'),
                                  ('079.20','COXSACKIE VIRUS INF NOS','none'),
                                  ('079.30','RHINOVIRUS INFECT NOS','none'),
                                  ('079.40','HUMAN PAPILLOMAVIRUS','none'),
                                  ('079.50','RETROVIRUS, UNSPECIFIED','none'),
                                  ('079.51','HTLV-1 INFECTION OTH DIS','none'),
                                  ('079.52','HTLV-II INFECTN OTH DIS','none'),
                                  ('079.53','HIV-2 INFECTION OTH DIS','none'),
                                  ('079.59','OTH SPECFIED RETROVIRUS','none'),
                                  ('079.60','RESPRTRY SYNCYTIAL VIRUS','none'),
                                  ('079.81','HANTAVIRUS INFECTION','none'),
                                  ('079.82','SARS ASSOC CORONAVIRUS','none'),
                                  ('079.88','OTH SPCF CHLAMYDIAL INFC','none'),
                                  ('079.89','OTH SPECF VIRAL INFECTN','none'),
                                  ('079.98','CHLAMYDIAL INFECTION NOS','none'),
                                  ('079.99','VIRAL INFECTION NOS','none'),
                                  ('080.00','LOUSE-BORNE TYPHUS','none'),
                                  ('081.00','MURINE TYPHUS','none'),
                                  ('081.10','BRILL''S DISEASE','none'),
                                  ('081.20','SCRUB TYPHUS','none'),
                                  ('081.90','TYPHUS NOS','none'),
                                  ('082.00','SPOTTED FEVERS','none'),
                                  ('082.10','BOUTONNEUSE FEVER','none'),
                                  ('082.20','NORTH ASIAN TICK FEVER','none'),
                                  ('082.30','QUEENSLAND TICK TYPHUS','none'),
                                  ('082.40','EHRLICHIOSIS NOS','none'),
                                  ('082.41','EHRLICHIOSIS CHAFEENSIS','none'),
                                  ('082.49','EHRLICHIOSIS NEC','none'),
                                  ('082.80','TICK-BORNE RICKETTS NEC','none'),
                                  ('082.90','TICK-BORNE RICKETTS NOS','none'),
                                  ('083.00','Q FEVER','none'),
                                  ('083.10','TRENCH FEVER','none'),
                                  ('083.20','RICKETTSIALPOX','none'),
                                  ('083.80','RICKETTSIOSES NEC','none'),
                                  ('083.90','RICKETTSIOSIS NOS','none'),
                                  ('084.00','FALCIPARUM MALARIA','none'),
                                  ('084.10','VIVAX MALARIA','none'),
                                  ('084.20','QUARTAN MALARIA','none'),
                                  ('084.30','OVALE MALARIA','none'),
                                  ('084.40','MALARIA NEC','none'),
                                  ('084.50','MIXED MALARIA','none'),
                                  ('084.60','MALARIA NOS','none'),
                                  ('084.70','INDUCED MALARIA','none'),
                                  ('084.80','BLACKWATER FEVER','none'),
                                  ('084.90','MALARIA COMPLICATED NEC','none'),
                                  ('085.00','VISCERAL LEISHMANIASIS','none'),
                                  ('085.10','CUTAN LEISHMANIAS URBAN','none'),
                                  ('085.20','CUTAN LEISHMANIAS ASIAN','none'),
                                  ('085.30','CUTAN LEISHMANIAS ETHIOP','none'),
                                  ('085.40','CUTAN LEISHMANIAS AMER','none'),
                                  ('085.50','MUCOCUTAN LEISHMANIASIS','none'),
                                  ('085.90','LEISHMANIASIS NOS','none'),
                                  ('086.00','CHAGAS DISEASE OF HEART','none'),
                                  ('086.10','CHAGAS DIS OF OTH ORGAN','none'),
                                  ('086.20','CHAGAS DISEASE NOS','none'),
                                  ('086.30','GAMBIAN TRYPANOSOMIASIS','none'),
                                  ('086.40','RHODESIAN TRYPANOSOMIAS','none'),
                                  ('086.50','AFRICAN TRYPANOSOMA NOS','none'),
                                  ('086.90','TRYPANOSOMIASIS NOS','none'),
                                  ('087.00','LOUSE-BORNE RELAPS FEVER','none'),
                                  ('087.10','TICK-BORNE RELAPS FEVER','none'),
                                  ('087.90','RELAPSING FEVER NOS','none'),
                                  ('088.00','BARTONELLOSIS','none'),
                                  ('088.81','LYME DISEASE','none'),
                                  ('088.82','BABESIOSIS','none'),
                                  ('088.89','OTH ARTHROPOD-BORNE DIS','none'),
                                  ('088.90','ARTHROPOD-BORNE DIS NOS','none'),
                                  ('090.00','EARLY CONG SYPH SYMPTOM','none'),
                                  ('090.10','EARLY CONGEN SYPH LATENT','none'),
                                  ('090.20','EARLY CONGEN SYPH NOS','none'),
                                  ('090.30','SYPHILITIC KERATITIS','none'),
                                  ('090.40','JUVENILE NEUROSYPH NOS','none'),
                                  ('090.41','CONGEN SYPH ENCEPHALITIS','none'),
                                  ('090.42','CONGEN SYPH MENINGITIS','none'),
                                  ('090.49','JUVENILE NEUROSYPH NEC','none'),
                                  ('090.50','LATE CONGEN SYPH SYMPTOM','none'),
                                  ('090.60','LATE CONGEN SYPH LATENT','none'),
                                  ('090.70','LATE CONGEN SYPH NOS','none'),
                                  ('090.90','CONGENITAL SYPHILIS NOS','none'),
                                  ('091.00','PRIMARY GENITAL SYPHILIS','none'),
                                  ('091.10','PRIMARY ANAL SYPHILIS','none'),
                                  ('091.20','PRIMARY SYPHILIS NEC','none'),
                                  ('091.30','SECONDARY SYPH SKIN','none'),
                                  ('091.40','SYPHILITIC ADENOPATHY','none'),
                                  ('091.50','SYPHILITIC UVEITIS NOS','none'),
                                  ('091.51','SYPHILIT CHORIORETINITIS','none'),
                                  ('091.52','SYPHILITIC IRIDOCYCLITIS','none'),
                                  ('091.61','SYPHILITIC PERIOSTITIS','none'),
                                  ('091.62','SYPHILITIC HEPATITIS','none'),
                                  ('091.69','SECOND SYPH VISCERA NEC','none'),
                                  ('091.70','SECOND SYPHILIS RELAPSE','none'),
                                  ('091.81','ACUTE SYPHIL MENINGITIS','none'),
                                  ('091.82','SYPHILITIC ALOPECIA','none'),
                                  ('091.89','SECONDARY SYPHILIS NEC','none'),
                                  ('091.90','SECONDARY SYPHILIS NOS','none'),
                                  ('092.00','EARLY SYPH LATENT RELAPS','none'),
                                  ('092.90','EARLY SYPHIL LATENT NOS','none'),
                                  ('093.00','AORTIC ANEURYSM, SYPHIL','none'),
                                  ('093.10','SYPHILITIC AORTITIS','none'),
                                  ('093.20','SYPHIL ENDOCARDITIS NOS','none'),
                                  ('093.21','SYPHILITIC MITRAL VALVE','none'),
                                  ('093.22','SYPHILITIC AORTIC VALVE','none'),
                                  ('093.23','SYPHIL TRICUSPID VALVE','none'),
                                  ('093.24','SYPHIL PULMONARY VALVE','none'),
                                  ('093.81','SYPHILITIC PERICARDITIS','none'),
                                  ('093.82','SYPHILITIC MYOCARDITIS','none'),
                                  ('093.89','CARDIOVASCULAR SYPH NEC','none'),
                                  ('093.90','CARDIOVASCULAR SYPH NOS','none'),
                                  ('094.00','TABES DORSALIS','none'),
                                  ('094.10','GENERAL PARESIS','none'),
                                  ('094.20','SYPHILITIC MENINGITIS','none'),
                                  ('094.30','ASYMPTOMAT NEUROSYPHILIS','none'),
                                  ('094.81','SYPHILITIC ENCEPHALITIS','none'),
                                  ('094.82','SYPHILITIC PARKINSONISM','none'),
                                  ('094.83','SYPH DISSEM RETINITIS','none'),
                                  ('094.84','SYPHILITIC OPTIC ATROPHY','none'),
                                  ('094.85','SYPH RETROBULB NEURITIS','none'),
                                  ('094.86','SYPHIL ACOUSTIC NEURITIS','none'),
                                  ('094.87','SYPH RUPT CEREB ANEURYSM','none'),
                                  ('094.89','NEUROSYPHILIS NEC','none'),
                                  ('094.90','NEUROSYPHILIS NOS','none'),
                                  ('095.00','SYPHILITIC EPISCLERITIS','none'),
                                  ('095.10','SYPHILIS OF LUNG','none'),
                                  ('095.20','SYPHILITIC PERITONITIS','none'),
                                  ('095.30','SYPHILIS OF LIVER','none'),
                                  ('095.40','SYPHILIS OF KIDNEY','none'),
                                  ('095.50','SYPHILIS OF BONE','none'),
                                  ('095.60','SYPHILIS OF MUSCLE','none'),
                                  ('095.70','SYPHILIS OF TENDON/BURSA','none'),
                                  ('095.80','LATE SYMPT SYPHILIS NEC','none'),
                                  ('095.90','LATE SYMPT SYPHILIS NOS','none'),
                                  ('096.00','LATE SYPHILIS LATENT','none'),
                                  ('097.00','LATE SYPHILIS NOS','none'),
                                  ('097.10','LATENT SYPHILIS NOS','none'),
                                  ('097.90','SYPHILIS NOS','none'),
                                  ('098.00','ACUTE GC INFECT LOWER GU','none'),
                                  ('098.10','GC (ACUTE) UPPER GU NOS','none'),
                                  ('098.11','GC CYSTITIS (ACUTE)','none'),
                                  ('098.12','GC PROSTATITIS (ACUTE)','none'),
                                  ('098.13','GC ORCHITIS (ACUTE)','none'),
                                  ('098.14','GC SEM VESICULIT (ACUTE)','none'),
                                  ('098.15','GC CERVICITIS (ACUTE)','none'),
                                  ('098.16','GC ENDOMETRITIS (ACUTE)','none'),
                                  ('098.17','ACUTE GC SALPINGITIS','none'),
                                  ('098.19','GC (ACUTE) UPPER GU NEC','none'),
                                  ('098.20','CHR GC INFECT LOWER GU','none'),
                                  ('098.30','CHR GC UPPER GU NOS','none'),
                                  ('098.31','GC CYSTITIS, CHRONIC','none'),
                                  ('098.32','GC PROSTATITIS, CHRONIC','none'),
                                  ('098.33','GC ORCHITIS, CHRONIC','none'),
                                  ('098.34','GC SEM VESICULITIS, CHR','none'),
                                  ('098.35','GC CERVICITIS, CHRONIC','none'),
                                  ('098.36','GC ENDOMETRITIS, CHRONIC','none'),
                                  ('098.37','GC SALPINGITIS (CHRONIC)','none'),
                                  ('098.39','CHR GC UPPER GU NEC','none'),
                                  ('098.40','GONOCOCCAL CONJUNCTIVIT','none'),
                                  ('098.41','GONOCOCCAL IRIDOCYCLITIS','none'),
                                  ('098.42','GONOCOCCAL ENDOPHTHALMIA','none'),
                                  ('098.43','GONOCOCCAL KERATITIS','none'),
                                  ('098.49','GONOCOCCAL EYE NEC','none'),
                                  ('098.50','GONOCOCCAL ARTHRITIS','none'),
                                  ('098.51','GONOCOCCAL SYNOVITIS','none'),
                                  ('098.52','GONOCOCCAL BURSITIS','none');");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DELETE FROM IcdCode;");
        }
    }
}
